"""
AegisOS — Standalone Database Setup
===================================
SQLAlchemy async engine, session factory, and base models.
Supports SQLite (zero dependencies) out of the box.
"""
from datetime import datetime
from typing import AsyncGenerator

from sqlalchemy import (
    Column, String, Float, Integer, Boolean, DateTime,
    JSON, Text, ForeignKey, Index
)
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker
from sqlalchemy.orm import declarative_base
from sqlalchemy.sql import func
from loguru import logger

from config import settings

# Engine setup — supports SQLite and PostgreSQL
is_sqlite = settings.database_url.startswith("sqlite")
connect_args = {"check_same_thread": False} if is_sqlite else {}

engine = create_async_engine(
    settings.database_url,
    echo=False,
    connect_args=connect_args,
)

AsyncSessionLocal = async_sessionmaker(
    bind=engine,
    class_=AsyncSession,
    expire_on_commit=False,
)

Base = declarative_base()


# Dependency
async def get_db() -> AsyncGenerator[AsyncSession, None]:
    async with AsyncSessionLocal() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise
        finally:
            await session.close()


# Models
class SensorReading(Base):
    """Time-series sensor telemetry from IoT/SCADA devices."""
    __tablename__ = "sensor_readings"

    id = Column(Integer, primary_key=True, index=True)
    sensor_id = Column(String(50), nullable=False, index=True)
    zone_id = Column(String(20), nullable=False, index=True)
    timestamp = Column(DateTime(timezone=True), server_default=func.now(), index=True)

    # Environmental readings
    temperature = Column(Float)          # °C
    pressure = Column(Float)             # bar
    humidity = Column(Float)             # %
    gas_level = Column(Float)            # ppm
    vibration = Column(Float)            # m/s²
    noise_level = Column(Float)          # dB
    air_quality = Column(Float)          # AQI

    # Machine readings
    rotational_speed = Column(Float)     # RPM
    torque = Column(Float)               # Nm
    tool_wear = Column(Float)            # min
    power_consumption = Column(Float)    # kW

    # Computed
    risk_score = Column(Float, default=0.0)     # 0-100
    anomaly_score = Column(Float, default=0.0)  # 0-1


class Alert(Base):
    """Safety alerts generated by the AI system."""
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    alert_id = Column(String(36), unique=True, index=True)  # UUID
    timestamp = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)

    severity = Column(String(20), nullable=False)   # low/medium/high/critical
    category = Column(String(50), nullable=False)   # gas_leak/fire/ppe/machine/compound
    zone_id = Column(String(20), nullable=False)
    sensor_id = Column(String(50), nullable=True)

    title = Column(String(200), nullable=False)
    description = Column(Text)
    recommended_actions = Column(JSON)   # List of action strings
    evidence = Column(JSON)              # Dict of contributing factors

    risk_score = Column(Float, default=0.0)
    is_compound = Column(Boolean, default=False)  # Multiple overlapping risks
    is_acknowledged = Column(Boolean, default=False)
    is_resolved = Column(Boolean, default=False)
    agent = Column(String(50))           # Which agent raised this


class WorkPermit(Base):
    """Work-to-permit system with AI conflict detection."""
    __tablename__ = "work_permits"

    id = Column(Integer, primary_key=True, index=True)
    permit_id = Column(String(36), unique=True, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    valid_from = Column(DateTime(timezone=True), nullable=False)
    valid_until = Column(DateTime(timezone=True), nullable=False)
    approved_at = Column(DateTime(timezone=True), nullable=True)

    permit_type = Column(String(50), nullable=False)  # hot_work/confined_space/electrical/height
    zone_id = Column(String(20), nullable=False)
    location_detail = Column(String(200))

    applicant_name = Column(String(100))
    applicant_id = Column(String(20))
    supervisor = Column(String(100))
    workers = Column(JSON)  # List of worker IDs

    work_description = Column(Text)
    hazards_identified = Column(JSON)
    control_measures = Column(JSON)
    ppe_required = Column(JSON)

    status = Column(String(20), default="pending")  # pending/approved/active/completed/cancelled
    risk_score = Column(Float, default=0.0)
    ai_conflicts = Column(JSON)   # AI-detected conflicts with other permits/sensors
    ai_recommendation = Column(String(20))  # approve/defer/deny


class Worker(Base):
    """Worker registry with real-time location and status."""
    __tablename__ = "workers"

    id = Column(Integer, primary_key=True, index=True)
    worker_id = Column(String(20), unique=True, index=True)
    name = Column(String(100), nullable=False)
    role = Column(String(50))
    department = Column(String(50))
    certification = Column(JSON)   # List of certifications

    current_zone = Column(String(20))
    last_seen = Column(DateTime(timezone=True))
    latitude = Column(Float)
    longitude = Column(Float)
    is_in_hazard_zone = Column(Boolean, default=False)
    status = Column(String(20), default="active")  # active/evacuated/incident


class Incident(Base):
    """Historical incidents for pattern learning and RAG."""
    __tablename__ = "incidents"

    id = Column(Integer, primary_key=True, index=True)
    incident_id = Column(String(36), unique=True, index=True)
    occurred_at = Column(DateTime(timezone=True), nullable=False)
    reported_at = Column(DateTime(timezone=True), server_default=func.now())

    incident_type = Column(String(50))    # near_miss/minor/major/fatality
    category = Column(String(50))         # gas_leak/fire/fall/equipment_failure
    zone_id = Column(String(20))
    severity = Column(String(20))

    title = Column(String(200))
    description = Column(Text)
    root_cause = Column(Text)
    contributing_factors = Column(JSON)
    corrective_actions = Column(JSON)

    casualties = Column(Integer, default=0)
    injuries = Column(Integer, default=0)
    property_damage_usd = Column(Float, default=0.0)

    investigation_complete = Column(Boolean, default=False)
    lessons_learned = Column(Text)


# Init
async def init_db():
    """Create all tables if they don't exist."""
    try:
        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)
        logger.info("✅ Database tables created successfully")
    except Exception as e:
        logger.warning(f"Database initialization warning: {e}")
